### ISSUE TITLE
Allow continue on error

### ISSUE THREAD

**Issue by benpicco** [RIOT-OS/murdock-scripts#46]
Currently CI will abort the build on the first error.

But sometimes it is helpful to know all instances of a failure, either to better gauge the solution strategy (single affected board vs all boards are affected) or to find all affected platforms at once instead of having to do an iterative approach with wait times in between.

This could be solved by a new label "don't abort on error"

**Comment by kaspar030** [comment]
There's "CI: no fast fail" for PR builds which was honored by murdock scripts but didn't exist in RIOT-OS/RIOT. Working now, see e.g., `https://ci.riot-os.org/details/384b6f6012344eb3a74c42211db3a57b`.
